POST http://sumi-taylor.test/api/auth/register
Content-Type: application/json

{
  "name": "admin",
  "email": "sumi@gmail.com",
  "password": "password"
}

###
POST http://sumi-taylor.test/api/auth/login
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "password"
}

###
DELETE http://sumi-taylor.test/api/auth/logout
